{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\n當用戶輸入特定文字消息時，會回傳按鍵模板消息。\\n\\n'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "當用戶輸入特定文字消息時，會回傳按鍵模板消息。\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "\n",
    "啟用伺服器基本樣板\n",
    "\n",
    "\"\"\"\n",
    "# 引用Web Server套件\n",
    "from flask import Flask, request, abort\n",
    "\n",
    "# 從linebot 套件包裡引用 LineBotApi 與 WebhookHandler 類別\n",
    "from linebot import (\n",
    "    LineBotApi, WebhookHandler\n",
    ")\n",
    "\n",
    "# \n",
    "from linebot.exceptions import (\n",
    "    InvalidSignatureError\n",
    ")\n",
    "\n",
    "# 將消息模型，文字收取消息與文字寄發消息 引入\n",
    "from linebot.models import (\n",
    "    MessageEvent, TextMessage, TextSendMessage,\n",
    ")\n",
    "\n",
    "# 載入設定檔\n",
    "\n",
    "import json\n",
    "secretFileContentJson=json.load(open(\"../line_secret_key\",'r',encoding=\"utf-8\"))\n",
    "server_url=secretFileContentJson.get(\"server_url\")\n",
    "\n",
    "\n",
    "# 設定Server啟用細節\n",
    "app = Flask(__name__,static_url_path = \"/images\" , static_folder = \"../images/\" )\n",
    "\n",
    "# 生成實體物件\n",
    "line_bot_api = LineBotApi(secretFileContentJson.get(\"channel_access_token\"))\n",
    "handler = WebhookHandler(secretFileContentJson.get(\"secret_key\"))\n",
    "\n",
    "# 啟動server對外接口，使Line能丟消息進來\n",
    "@app.route(\"/\", methods=['POST'])\n",
    "def callback():\n",
    "    # get X-Line-Signature header value\n",
    "    signature = request.headers['X-Line-Signature']\n",
    "\n",
    "    # get request body as text\n",
    "    body = request.get_data(as_text=True)\n",
    "    app.logger.info(\"Request body: \" + body)\n",
    "\n",
    "    # handle webhook body\n",
    "    try:\n",
    "        handler.handle(body, signature)\n",
    "    except InvalidSignatureError:\n",
    "        abort(400)\n",
    "\n",
    "    return 'OK'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Button篇\n",
    "    設定模板消息，指定其參數細節。\n",
    "\n",
    "'''\n",
    "\n",
    "\n",
    "#引入所需要的消息與模板消息\n",
    "from linebot.models import (\n",
    "    MessageEvent, TemplateSendMessage , PostbackEvent\n",
    ")\n",
    "\n",
    "#引入按鍵模板\n",
    "from linebot.models.template import(\n",
    "    ButtonsTemplate\n",
    ")\n",
    "\n",
    "\n",
    "'''\n",
    "alt_text: Line簡覽視窗所出現的說明文字\n",
    "template: 所使用的模板\n",
    "ButtonsTemplate: 按鍵模板\n",
    "    thumbnail_image_url: 展示圖片\n",
    "    title: 標題\n",
    "    text: 說明文字\n",
    "    actions: 模板行為所使用的行為\n",
    "    data: 觸發postback後用戶回傳值，可以對其做商業邏輯處理\n",
    "\n",
    "'''\n",
    "buttons_template_message = TemplateSendMessage(\n",
    "    alt_text='Buttons template',\n",
    "    template=ButtonsTemplate(\n",
    "        title='更多幫助',\n",
    "        text='請點擊下方按鈕獲得更多幫助',\n",
    "        actions=[\n",
    "              {\n",
    "        \"type\": \"uri\",\n",
    "        \"label\": \"動作 1\",\n",
    "        \"uri\": \"tel://3345678\"\n",
    "      },\n",
    "          {\n",
    "            \"type\": \"postback\",\n",
    "            \"label\": \"企業，查找商業結合方案\",\n",
    "            \"text\": \"[::text:]尋找BD\",\n",
    "            \"data\": \"Data1\"\n",
    "          },\n",
    "          {\n",
    "            \"type\": \"postback\",\n",
    "            \"label\": \"開發者，尋求教學\",\n",
    "            \"text\": \"[::text:]求助專家\",\n",
    "            \"data\": \"Data2\"\n",
    "          }\n",
    "        ],\n",
    ")\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "設計一個字典\n",
    "\n",
    "'''\n",
    "template_message_dict = {\n",
    "    \"[::text:]more\":buttons_template_message\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "# 用戶發出文字消息時， 按條件內容, 回傳照片地圖\n",
    "@handler.add(MessageEvent, message=TextMessage)\n",
    "def handle_message(event):\n",
    "    line_bot_api.reply_message(\n",
    "        event.reply_token,\n",
    "        template_message_dict.get(event.message.text)\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "#用戶點擊button後，觸發postback event，對其回傳做相對應處理\n",
    "# handler如果你收到回傳事件(暗事件)，做下面的處理\n",
    "@handler.add(PostbackEvent)\n",
    "def handle_post_message(event):\n",
    "    \n",
    "    # 取個資\n",
    "    user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "    \n",
    "    # 若回傳事件的隱藏資料為Data1做下面的方法\n",
    "    if (event.postback.data.find('Data1')== 0):\n",
    "        with open(\"../user_profile_business.txt\", \"a\") as myfile:\n",
    "            myfile.write(json.dumps(vars(user_profile),sort_keys=True))\n",
    "            myfile.write('\\r\\n')\n",
    "            line_bot_api.reply_message(\n",
    "            event.reply_token,\n",
    "                TextMessage(\n",
    "                    text='請稍待，會有專人與您聯繫'\n",
    "                )\n",
    "            )\n",
    "            \n",
    "    # 若回傳事件的隱藏資料為Data2做下面的方法\n",
    "    elif (event.postback.data.find('Data2') == 0):\n",
    "        with open(\"../user_profile_tutorial.txt\", \"a\") as myfile:\n",
    "            myfile.write(json.dumps(vars(user_profile),sort_keys=True))\n",
    "            myfile.write('\\r\\n')\n",
    "            line_bot_api.reply_message(\n",
    "            event.reply_token,\n",
    "                TextMessage(\n",
    "                    text='請稍待，我們會派專家與您聯繫'\n",
    "                )\n",
    "            )\n",
    "    else:\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [26/Jul/2020 14:49:42] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:49:48] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:49:49] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-07-26 14:50:00,082] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:00] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:04] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-07-26 14:50:05,801] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:05] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:06] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:21] \"\u001b[37mGET /images/004.png HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:22] \"\u001b[37mGET /images/003.jpeg HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-07-26 14:50:28,981] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:28] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-26 14:50:32,315] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:32] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-26 14:50:33,409] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [26/Jul/2020 14:50:33] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-26 14:50:34,726] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:34] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-26 14:50:35,556] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-9-9b79bba4b506>\", line 50, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\webhook.py\", line 260, in handle\n",
      "    func(event)\n",
      "  File \"<ipython-input-12-cc7f906331d7>\", line 4, in handle_message\n",
      "    line_bot_api.reply_message(\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in reply_message\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "  File \"C:\\Users\\User\\anaconda3\\lib\\site-packages\\linebot\\api.py\", line 103, in <listcomp>\n",
      "    'messages': [message.as_json_dict() for message in messages],\n",
      "AttributeError: 'NoneType' object has no attribute 'as_json_dict'\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:35] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Jul/2020 14:50:37] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "啟動Server\n",
    "\n",
    "'''\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host='0.0.0.0')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
